CONTRIBUTING.md
admin/api_clusters.go
admin/api_events.go
admin/api_monitoring_and_logs.go
admin/api_performance_advisor.go
examples/regions/example_cluster_regions.go
tools/config/go-templates/api.mustache

Fixing blocker for CLOUDP-172196 - removing redundant reflect. 
NOTE: openapi generator adds imports for reflection that we cannot remove in the template.

CLOUDP-172196: reflect error when query contains array of objects

---

admin/doc.go
core/doc.go
tools/config/config.yaml
tools/config/go-templates/doc.mustache

Add docs to all packages in the SDK (clarify the roles of the packages to end users. 
Without docs.go - go documentation lists all the files for the package without any context.

CLOUDP-176385: add docs.go for clarity

---

admin/api_events.go
openapi/atlas-api-transformed.yaml
tools/transformer/src/atlasTransformations.js
tools/transformer/src/transformations/swapArray.js

Jira: CLOUDP-173481
Follow-up on https://github.com/mongodb/atlas-sdk-go/pull/35
Correcting typo and moving return statement outside of loop to appropriately generate `EventTypeForOrg` as a string array (temporary workaround)

CLOUDP-173481: amend array transformation for org events

---

tools/transformer/src/transformations/swapArray.js

Dev will have those values renamed but we need that transformation for production.

fix: Array workaround -  do not throw error when model name is changed

---

admin/model_fts_mappings.go
admin/model_index_options.go
openapi/atlas-api-transformed.yaml
openapi/atlas-api.yaml
tools/transformer/src/atlasTransformations.js
tools/transformer/src/transformations/additionalPropertiesObject.js
tools/transformer/src/transformations/index.js

New transformation is required to relax json parser for cases when we want to support object and array.
Api with additionalProperties properly generates an map[string]map[string]interface{} objects for SDK.
However in multiple cases for search all we need is  map[string]interface{}

CLOUDP-181547: transformation for nested hashmaps

---

.github/dependabot.yml

We do have codeowners in place for all repo so dependabot will not be able to add those

fix: remove unneeded reviewers

---

test/example_client_test.go

Rename file to match expected naming practices for examples

fix: rename example file to match expected naming

---

.github/workflows/autoupdate-dev.yaml

Nit: We need to clearly inform developers that dev channel changes should not be merged.
We have number of other mitigations in place including branch protection but they still can be avoided when no clear message about the purpose of the PR is provided.

CLOUDP-184833: include do not merge just in case someone approves PR

---

admin/client.go
tools/config/go-templates/client.mustache

We need to be able to set the values of the generic open API error for purpose of testing and mocking
Alternatively, we could use reflection but that seems overly problematic. 

CLOUDP-181568: improve unit testing and mocking for API errors

---

docs/doc_1_concepts.md
internal/core/version.go

Updates to concepts to include a versioning strategy for the sdk go.
I have picked a long format for the docs but it can be simplified if we want.

CLOUDP-187090: Release bump and versioning strategy for go sdk

---

Makefile

Minor correction to use path (local) instead of a package (global)

CLOUDP-185429: use full path for the test case

---

.github/CODEOWNERS

We strive to ping docs team only for manual changes and have reviewer assignment actionable.

fix: remove docs from readme.md change as it is autogenerated

---

tools/scripts/fetch.sh

Automatic fetch operation should no longer be fixed to 2023-02-01 Resource version and rely on versioning metadata.
1. Current version works unchanged
```
▶ make fetch_openapi                                    
./scripts/fetch.sh
~/Projects/cloud/atlas-sdk-go/openapi ~/Projects/cloud/atlas-sdk-go/tools
Fetching versions from https://cloud.mongodb.com/api/openapi/versions
Fetching api from https://cloud.mongodb.com/api/openapi/spec/2.0?version=2023-02-01&filter=sdk to atlas-api.yaml
~/Projects/cloud/atlas-sdk-go/openapi
```
2. Previous versions work properly as well. 
```
./scripts/fetch.sh
~/Projects/cloud/atlas-sdk-go/openapi ~/Projects/cloud/atlas-sdk-go/tools
Fetching versions from https://cloud.mongodb.com/api/openapi/versions
Fetching api from …
```

CLOUDP-155909: fetch should use dynamic version from versions.json file

---

.github/workflows/autorelease.yaml
.github/workflows/autoupdate-dev.yaml
.github/workflows/autoupdate-prod.yaml
.github/workflows/shellcheck.yml
scripts/add-copy.sh

Based on support and security review of our Github actions integration we have done a number of steps to ensure no script injections are possible and we cannot have to third party vendors attack. 
Adding SHA commits is going to be automatically supported by dependabot.
For more info see: 
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions

chore: Use git refs for all the actions for security hardening

---

.github/workflows/autoupdate-prod.yaml

Use generated source code as indication for the creation of the release PR.

CLOUDP-193204: Ignore empty generation PRs. 

---

docs/doc_1_concepts.md
docs/doc_last_reference.md
tools/config/go-templates/README.mustache

Based on feedback from the product we need to adjust our experimental section for clarity.
Removed internal parts of the experimental section covering update of the operationIds

CLOUDP-194380: revisit experimental section in docs

---

.github/workflows/autoupdate-preview.yaml
.github/workflows/autoupdate-prod.yaml
.github/workflows/breaking-changes.yaml

Detect breaking changes in the SDK using separate optional jobs.
Job failing will mean that we have breaking changes in place and need to take action by documenting changes.
1. Job always compares with the main branch
2. It lists all the incompatibilities (it will be subject to false positives which is fine)
3. It is introduced as a separate step so it will be optional and only act as a helper for developers to verify breaking changes
A lot of improvements in the upstream job is needed to be able to use this action for automatic merges.
I will be looking to help improve that job so we can rely on it with our current automation and minimize false positives, duplicates etc.
https://github.com/mongodb/atlas-sdk-go/actions/runs/5950387722/job/16138071247

CLOUDP-195429: detect breaking changes in the SDK

---

.github/workflows/issues.yml

The JIRA token has been already rotated in the repo. Once this PR is merged, we can enable the workflow again.
Link to any related issue(s): [INTMDB-1032]( https://jira.mongodb.org/browse/INTMDB-1032)
Follow up PR of https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1422

fix: update issue.yml to use issue number as Ticket title

---

.github/workflows/autorelease.yaml

Paths should be git repository paths from git diff.
`./` is not valid prefix as paths aren't executed by bash - they are matched against git diff.

CLOUDP-197445: paths to the version.go file

---

.github/workflows/autoupdate-preview.yaml
.github/workflows/autoupdate-prod.yaml

Order of the gh actions steps causing SDK generation to fail when go version is set before checkout.

fix: order of the gh actions steps

---

.github/workflows/breaking-changes.yaml

Exclude breaking changes job when breaking changes documentation was provided (and major version was released)
Currently due to an issue in upstream library major releases trigger very large diff that we want to avoid generating.

fix: do not run breaking changes on major release

---

.github/workflows/autorelease.yaml

Since releases are very reliable and have been tested over the last +5 releases we can remove draft mode for releases.
Currently, every release requires manual button push that we did not document as it was only temporary measure.
> NOTE: Removing draft mode implies that S3 folder used for major releases contains the required index.html file. 
If not, file should be uploaded before merging auto-update PR. Draft mode gives us time to validate if s3 bucket is present.

fix: remove draft mode from autorelease script

---

.github/workflows/breaking-changes.yaml

Breaking changes job has many false positives and it is failing almost always on the generated PRs. 
I have made a number of fixes upstream that need to be merged. 
For the time being, we do not want our builds to fail but will use action output for inspecting possible breaking changes.

task: disable breaking changes job from failing

---

tools/releaser/scripts/new-version.sh
tools/releaser/scripts/setghenv.sh

Minor improvements to the release automation that have failed due to missing fprint binary in github actions:
```
Extracted version versions.json: '20230201'.
./releaser/scripts/setghenv.sh: line 26: fprintf: command not found
```

CLOUDP-202699: use echo for release script instead of fprint

---

.github/workflows/autoupdate-prod.yaml
tools/releaser/scripts/breaking-changes.sh

Breaking changes started to return no results if the base path of the repository is not in the current directory.
I'm going to fix the issue upstream. Providing a workaround to unblock us in the SDK

CLOUDP-206550: regression in breaking changes

---

admin/api_data_federation.go
admin/api_monitoring_and_logs.go
admin/api_online_archive.go
admin/client.go
docs/doc_5_best_practices.md
docs/docs/DataFederationApi.md
docs/docs/MonitoringAndLogsApi.md
docs/docs/OnlineArchiveApi.md
examples/download/downloadLogs.go
tools/config/go-templates/client.mustache
tools/scripts/generate.sh
tools/scripts/generate_docs.sh
tools/scripts/generate_tests.sh

Currently we are creating temp files on every API that downloads a file from network, this changes it to keep it in memory as oppose to write to disk
Link to any related issue(s):  https://jira.mongodb.org/browse/CLOUDP-209888

CLOUDP-209888: Remove temp file creation

---

tools/releaser/scripts/update-version.sh

Reason: The folder is required for scripts to function
Adds folder required by breaking changes engine. 
Automatically removes folder if it was removed.

fix: add breaking changes folder

---

docs/doc_1_concepts.md

Added documentation on the `read only` and `write only` fields as a follow-up from a previous PR.
Previous change: [CLOUDP-219156](https://jira.mongodb.org/browse/CLOUDP-219156)

CLOUDP-221643: Document the meaning of read/write only fields

---

tools/transformer/src/transformations/oneOf.js

Add error information for situations when OpenAPI schema contains base types (int,bool, string etc.) instead of objects.
We do have error returned for this cases but were missing explanation why this is happening.
OneOf of mixed types cannot be represented correctly. When dealing with objects we can merge them but any other form of base types will introduce invalid behaviour.

task: fix message in transformation engine

---

.github/workflows/autoupdate-prod.yaml

Cron job can run during the night to enable other timezones.

task: change cron job for Autoupdate PRs to start earlier

---

.github/workflows/autorelease.yaml

Triggers Go proxy cache refresh when a release is done

chore: Triggers Go proxy cache refresh

---

.github/workflows/pr.yml

Minot fix to prevent cache issues for golangci-lint

task: remove cache from go installation

---

examples/go.mod
examples/go.sum
go.mod
internal/core/version.go

With recent versions of golang go mod tidy updates go mod and adds tooling. 
That is not desired for SDK. Adding manual to the golang version.

task: update golang version of the SDK

---

tools/transformer/src/atlasTransformations.js
tools/transformer/src/engine/transformers.js

CLOUDP-252756
Transformation restores previous state for the OpenAPI after recent major release.
Results will be visible in the generated OpenAPI release. I have tested transformation with different versions in OpenAPI.  I have designed it to automatically. 
Since this is one singular case we not going to make this an "official" transformation and keep it as placeholder to fix issue with search. We already have other placeholder in place at the moment.

CLOUDP-252756 - transform Search Schema

---

tools/.npmrc
tools/package-lock.json
tools/package.json

Be strict on the node version 
if you don't have the correct version installed you'll get
```
npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: openapi-generation-tools@0.1.0
npm ERR! notsup Not compatible with your version of node/npm: openapi-generation-tools@0.1.0
npm ERR! notsup Required: {"node":">= 18","npm":">= 10"}
npm ERR! notsup Actual:   {"npm":"9.8.1","node":"v18.18.2"}
```

task: be strict on the node version we use

---

tools/transformer/src/duplicate.ignore.json

Since Search API is now transformed we do not need it to be ignored in detection of duplicates. 
This will prevent from introducing another set of duplicated models for search in the future.
The new resource version should no longer have those duplicates as well.
CI/CD passes

task: remove search api from ignores

---

docs/doc_5_best_practices.md

Due to the use of a code block within a bullet, we can't import the SDK docs without editing the downloaded file. This fixes that issue.

Adds a line break to prevent issues importing to docs

---

.github/workflows/autoupdate-preview.yaml
.github/workflows/autoupdate-prod.yaml
CONTRIBUTING.md
Makefile
tools/scripts/generate.sh

CLOUDP-252392
Reused existing make file and added documentation for goimports binary that is now integral part of the SDK.
- Successfully run [autoupdate-preview job from](https://github.com/mongodb/atlas-sdk-go/actions/runs/9663629705) branch.
- Successfully run `make openapi-pipeline` in evergreen
Added documentation in order to install required tool on the developers machines
- Initially implemented goimports installation during generate phase however this approach would have hidden this tool from developers can cause futher issues with local dev setup.
- Investigated embedding all binaries into go.mod with ability to install them:
```
tools=...
go install $tools
```

CLOUDP-252392: unify go imports installation

---

.github/CODEOWNERS

Change only for integrations team to get notifications on the automatic SDK PRs. 
o other impact as all integrations team members already have full write access on the repository and monitoring PRs.
This step is required for the integration team to get new PR notifications and shadow PR reviews.
Individual members can still manage their notification settings to adjust notifications.
On call rota determines person who should be reviewing PR (still APIx1 for the moment)

CLOUDP-268814 - Integrations team notified for the new atlas-sdk-go PR reviews.

---

tools/releaser/scripts/breaking-changes.sh

Minor cleanup for the breaking changes script from debug logging we added recently to understand breaking changes error codes.
Breakingchanges cmd always returns 0 status independent from the breaking changes in github actions environment,
which is not desired behaviour: https://github.com/joelanford/go-apidiff/blob/main/action.yml#L64-L72

task: cleanup breaking changes

---

admin/client.go
test/example_error_test.go
tools/config/go-templates/client.mustache

Adding missing SDK error formatting introduced recently by us in backend.
1. Review example file 
2. Tests should be passing (example is an test)
3. Review template

CLOUDP-276381: adding formatting to SDK

---

admin/client.go

Adds status code to errors when code >= 3xx
Link to any related issue(s): CLOUDP-270745

chore: Adds status code to errors when code >= 3xx

---

auth/code/device_flow.go
auth/code/device_flow_test.go
auth/code/doc.go
auth/code/oauth.go
auth/code/oauth_test.go
auth/code/token.go

Cleanup in unused auth module. 
Auth Module were never used moving to subpackage. In the follow up PRs we will be introducing alternative authentication methods and we need auth module to be part of the subpackage.
For more info see: https://github.com/mongodb/atlas-sdk-go/pull/429

task: move unused codebase to the new package

---

.github/workflows/autoupdate-prod.yaml
tools/CONTRIBUTING.md
tools/releaser/scripts/breaking-changes.sh

Breaking changes engine improvements. Fixes commit to compare with if there are SDK breaking changes.
Link to any related issue(s): CLOUDP-261727
Before this PR, changes for API spec in PR 290 showed this. There are breaking changes so there should be a major release but it isn't.
https://github.com/mongodb/atlas-sdk-go/actions/runs/11344491264/job/31549328777
https://github.com/mongodb/atlas-sdk-go/pull/433/files#diff-429330c1bd13608c65647ca92e155a5d314420aac3bc6438011f00754a44d652
With this PR there is a new major release, and file `tools/releaser/breaking_changes/v20240805005.md` is generated correctly:
https://github.com/mongodb/atlas-sdk-go/actions/runs/11363986358/job/31609079124
https://github.com/mongodb/atlas-sdk-go/pull/440/files#diff-429330c1bd13608c65647ca92e155a5d314420aac3bc6 …

CLOUDP-261727: Breaking changes engine improvements

---

.github/CODEOWNERS

TL;DR - APIx Integrations approval is required for all PRs on the SDK-go
APIx1 will still be notified, but cannot merge without APIx Integrations approval.

task: update codeowners to list only APIx Integrations team

---

admin/atlas_client.go
auth/credentials/api.go
auth/credentials/oauth.go
auth/credentials/oauth_test.go
internal/core/client.go
internal/core/constants.go
tools/config/go-templates/atlas_client.mustache

Added support for default and custom User Agent in newly introduced `OAuthTokenSource`. Also moved now shared default User Agent, DefaultCloudURL and ClientName to the `core` package for sharing between the Admin client and the token endpoints.
[CLOUDP-279931](https://jira.mongodb.org/browse/CLOUDP-279931)
Extended `credentials/oauth_test.go` for testing default and custom User Agent.

CLOUDP-279931: Add ability to control user agent for token endpoints

---

examples/service_account_management/sa_management.go

Add extra messages
Enforce the lowest possible permission in example.
▶ go run examples/service_account_management/sa_management.go 
Created new service account.
Projects size: 1
Created service account was deleted.

CLOUDP-294985: created SA only needs read permission.

---

.github/workflows/autoupdate-preview.yaml
tools/releaser/scripts/extract-version.sh
tools/scripts/fetch.sh

Please include a summary of the fix/feature/change, including any relevant motivation and context.
Local tests 
```shell
➜  tools git:(update-versions) ✗ ./scripts/fetch.sh             
~/workplace/atlas-sdk-go/openapi ~/workplace/atlas-sdk-go/tools
Fetching versions from https://raw.githubusercontent.com/mongodb/openapi/refs/heads/main/openapi/v2/versions.json
Fetching OAS file for version 2025-02-19
Fetching api from https://raw.githubusercontent.com/mongodb/openapi/refs/heads/main/openapi/v2/openapi-2025-02-19.yaml to atlas-api.yaml
~/workplace/atlas-sdk-go/openapi
➜  tools git:(update-versions) ✗ ./releaser/scripts/extract-version.sh
Extracted version from version.go file: 'v20241113005.0.0'. Resource Version: '20241113'
Major: v20241113005' Minor: 0
Extracted version versions.json: …
```

CLOUDP-261809: update sdk to use mongodb/openapi

---

tools/scripts/fetch.sh

Script extension had wrong bracket.
Covers: https://github.com/mongodb/atlas-sdk-go/actions/runs/13496682941/job/37705444807

task: script extension

---

internal/core/version.go
tools/releaser/scripts/breaking-changes.sh
tools/releaser/scripts/new-version.sh

Fixes new-version.sh to avoid leaking version variables when calling breaking-changes script
Link to any related issue(s): CLOUDP-302378
- Ran the generation [here](https://github.com/mongodb/atlas-sdk-go/actions/runs/13515826810/job/37764226741) and it updated `version.go` correctly
- See the resulting PR opened by the bot in #521 
- As seen by the final line in `Release Update` [step](https://github.com/mongodb/atlas-sdk-go/actions/runs/13450749746/job/37584642959#step:11:466):
`Creating new version.go file with v20241113005.0.0 and resource version: 20250219`
The `SDK_VERSION` got accidentally overwritten.
This is due to the call to
`source "$script_path/breaking-changes.sh"` that was changed in #499 to `source "$script_path/extract-version.sh"`  leading to overwrite of `SDK_VERSION` …

chore: Fixes new-version.sh to avoid accidentally overwriting version variables when calling breaking-changes script

---

tools/scripts/generate_mocks.sh

Link to any related issue(s): CLOUDP-306814
- dependabot udpated go version from 1.22 to 1.23 [Pull Request #531](https://github.com/mongodb/atlas-sdk-go/pull/531)
- mocked generation was not made in https://github.com/mongodb/atlas-sdk-go/pull/533 due to error when calling mockery image
- `err: exit status 1: stderr: go: go.mod requires go >= 1.23.0 (running go 1.22.1; GOTOOLCHAIN=local)`
Fix implies using updated version of mockery image which support Go 1.24.1: https://hub.docker.com/layers/vektra/mockery/v2.53.2/images/sha256-cecc555d7d3369479590834cff7885413675017ff53133a7751c9b6294745d13. Ran both the failing version and new version locally, no changes required in generated mocks.

chore: Bump fixed version of mockery docker image

---

.github/workflows/pr.yml
.golangci.yml
Makefile
auth/clientcredentials/clientcredentials.go

Upgrades golangci-lint to v2 using the [migration guide](https://golangci-lint.run/product/migration-guide/), follow example in: https://github.com/mongodb/openapi/pull/616

chore: Upgrades golangci-lint to v2

---

admin/model_stream_processor_metric_threshold.go
internal/core/version.go
openapi/atlas-api-transformed.yaml
tools/transformer/src/atlasTransformations.js
tools/transformer/src/field.transformations.json
tools/transformer/src/transformations/fields.js
tools/transformer/src/transformations/index.js

Atlas Go SDK was autogenerated and included this [change](https://github.com/mongodb/atlas-sdk-go/pull/545/files#diff-05814b892b574662623416b5fa87eece63ecf7a2e7b5abf8bdafaedbe9fbf414R35) in the release [v20250312](https://github.com/mongodb/atlas-sdk-go/releases/tag/v20250312001.0.0), which removed GreaterThanRawThreshold and replaced it with StreamProcessorMetricThreshold.
In the [OpenAPI spec](https://raw.githubusercontent.com/mongodb/atlas-sdk-go/refs/heads/main/openapi/atlas-api.yaml), GroupAlertsConfig is defined as OneOf of multiple schemas. The latest one added, StreamProcessorMetricAlertConfigViewForNdsGroup has caused a change in the [transformed OpenAPI spec](https://github.com/mongodb/atlas-sdk-go/blob/92ba675c039b5e9427084c208fc35f957dee2385/openapi/atlas-api-transformed.yaml#L …

fix: Makes specified fields optional in their respective schemas

---

.github/workflows/autorelease.yaml
.github/workflows/autoupdate-preview.yaml
.github/workflows/autoupdate-prod.yaml
.github/workflows/issues.yml
.github/workflows/pr.yml
.github/workflows/shellcheck.yml
.github/workflows/stale.yml

Pin SHAs in Github Actions following security best practices.  This is a follow-up to https://github.com/mongodb/atlas-sdk-go/pull/550
Link to any related issue(s): CLOUDP-306816.

chore: Pin SHAs in Github Actions

---

examples/aws_cluster/aws.go

Link to any related issue(s): CLOUDP-311082
In prod sharded clusters must have instance size >= M30.

chore: Fix instance size of sharded cluster example

---

admin/client.go
tools/config/go-templates/client.mustache

Export SDK functions needed by Terraform `UntypedAPICall`.   Manual changes in this PR are only in client.mustache.
A new struct `UntypedClient` is created so `APICient` namespace is not polluted. Changes are minimized so current private functions are kept unchanged.
This was discussed and prefered to have duplicated code like in https://github.com/mongodb/terraform-provider-mongodbatlas/pull/3326.
Although they are exported functions that potentially can be used by anybody, we don't expect them to be used as they're not documented, and breaking changes are acceptable in these functions.
Link to any related issue(s): CLOUDP-316444

chore: Export SDK functions needed by Terraform UntypedAPICall func

---

.github/workflows/autoupdate-preview.yaml
.github/workflows/pr.yml
Makefile
tools/releaser/scripts/preview-version.sh

Fix SDK preview linter issues.  
It's failing because file `auth/clientcredentials/clientcredentials_test.go` has imports:
```
"github.com/stretchr/testify/assert"
"go.mongodb.org/atlas-sdk/v20250312003/auth"
```
and when they're changed to use Preview namespace, they become:
```
"github.com/stretchr/testify/assert"
"github.com/mongodb/atlas-sdk-go/auth"
```
So they're not ordered alphabetically anymore and linter fails.

chore: Fix SDK preview linter issues

---

tools/scripts/fetch.sh

Exclude upcoming OpenAPI versions. This will fix the SDK Preview PRs.
Example of generated SDK Preview PR: https://github.com/mongodb/atlas-sdk-go/pull/618

chore: Exclude upcoming OpenAPI versions

---

.github/CODEOWNERS

Removes docs team from codeowners to avoid mandatory review on documentation changes. Docs in SDK come from upstream so there is no point on having it reviewed here

chore: Removes docs team from codeowners to avoid mandatory review on documentation changes

---

tools/transformer/README.md
tools/transformer/__tests__/input.json
tools/transformer/__tests__/transformations.test.js
tools/transformer/src/atlasTransformations.js
tools/transformer/src/transformations/index.js
tools/transformer/src/transformations/operationId.js

Adds support for using `x-xgen-operation-id-override` to override operation IDs in the OAS transformation. The transformation will replace operation IDs with the value of `x-xgen-operation-id-override` for the operation (if present), and then remove the extension from the transformed spec.
No changes to the client code since the OAS does not yet have `x-xgen-operation-id-override` values. When these are added to existing operations, breaking changes will occur.
Jira: [CLOUDP-331824](https://jira.mongodb.org/browse/CLOUDP-331824)
Usage of `x-xgen-operation-id-override` and breaking changes TBD in a later ticket.

feat: Operation ID override support to transformation
