.github/dependabot.yml

Moving dependabot updates to apix-1

CLOUDP-176390: Dependabot updates

---

README.md

Minor fix for indentiation of the source code and header levels

CLOUDP-175576: indentation in readme file

---

docs/README.md
scripts/toc.sh

Fixing small issues where docs links have been prefixed by folder.

CLOUDP-176574: docs links are now local

---

tools/transformer/__tests__/transformations.test.js
tools/transformer/src/engine/readers.js
tools/transformer/src/engine/transformers.js
tools/transformer/src/transformations/allOf.js

`allOf` references to parents that have no properties or required properties should be removed as part of the `allOf` transformation.
Before:
```
CreateEndpointRequest:
type: object
oneOf:
- $ref: "#/components/schemas/CreateAWSEndpointRequest"
- $ref: "#/components/schemas/CreateAzureEndpointRequest"
- $ref: "#/components/schemas/CreateGCPEndpointGroupRequest"
CreateAWSEndpointRequest:
type: object
allOf:
- $ref: '#/components/schemas/ApiAtlasCreateEndpointRequestView'
- type: object
properties: ...
CreateAzureEndpointRequest:
type: object
allOf:
- $ref: '#/components/schemas/ApiAtlasCreateEndpointRequestView'
- type: object
properties: ...
CreateGCPEndpointGroupRequest:
type: object
allOf:
- $ref: '#/components/schemas/ApiAtlasCreateEndpointRequestView'
- type: object
properties: ... …
```

fix: enable allOf transformation for parents with no properties

---

.github/workflows/autoupdate-dev.yaml
.github/workflows/autoupdate-prod.yaml
.github/workflows/pr.yml
.github/workflows/release-check.yml

CI/CD process is using some old versions of Golang. 
Unifying everything to run on 1.20.

CLOUDP-179041: unify go version for ci/cd

---

docs/README.md
docs/doc_1_reference.md
tools/config/go-templates/README.mustache

Feedback from community. Documentation were confusing/missing reference

CLOUDP-179266: make explicit name for reference doc

---

scripts/toc.sh

Changed installation folder for toc tool.

CLOUDP-180035: folder change for toc

---

tools/transformer/src/discriminator.ignore.json

Remove discriminator ignore that have been fixed already.

fix: remove unneded discriminator ignore instance

---

docs/README.md
docs/doc_1_concepts.md
docs/doc_2_error_handling.md
docs/doc_3_migration.md
docs/doc_4_authentication.md

Copy edits to the static docs files.
Link to any related issue(s): 
https://jira.mongodb.org/browse/DOCSP-30264
N/A- docs change only

(DOCSP-30264) Copy edits the static docs files

---

admin/utils.go
examples/db_users/db_users.go
tools/config/go-templates/utils.mustache

Providing an example of dbUser update

CLOUDP-180813: provide example for dbUser update

---

admin/api_programmatic_api_keys.go
openapi/atlas-api-transformed.yaml
openapi/atlas-api.yaml

Spec correction for createApiKeyAccessList - returning PaginatedApiUserAccessList

CLOUDP-180814: createApiKeyAccessList openApi Schema correction

---

docs/README.md
docs/doc_5_best_practices.md

Adding documentation for covering best practices for using SDK.
Based on issues seen with integrations
CLOUDP-181271

CLOUDP-181271: common errors and best practices documentation

---

docs/doc_3_migration.md

Update endpoint documentation link in migration page

---

CONTRIBUTING.md

Adding some of the corrections to the workflow in Contributing
We strive to ping the documentation team on dedicated PRs, containing only manual docs changes.
SDK docs review will be done thru Docs/OpenAPI so we do not need to duplicate efforts here as well send too many notifications
CC @sarahsimpers

fix: update contributing to reflect workflow for the docs reviews

---

tools/transformer/src/atlasTransformations.js

RegionConfig name is too generic. Changed to CloudRegionConfig

CLOUDP-170462: rename region config

---

internal/core/doc.go
internal/core/version.go

fix: bump version of the SDK

---

.github/workflows/autoupdate-dev.yaml

It is beneficial to get daily development changes as well as to track possible issues and inconsistencies.

fix: adjust schedule to update dev version daily

---

examples/db_users/db_users.go
examples/download/downloadLogs.go
examples/errors.go

CLOUDP-184833: minor fixes for the examples (panic errors)

---

examples/README.md

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Remove repeated line in examples documentation

---

README.md

The example in `README.md` did not work "out of the box", so I supplemented it such that the user can just copy and paste it into their code.

Fix example in `readme`

---

README.md

Correct invalid version import.

fix: import path with version

---

tools/transformer/README.md

CLOUDP-187065: remove note about extension

---

docs/doc_5_best_practices.md

Ensuring we have clarity about date handling in the SDK. 
Clarifies how to map date to the string and check for date existence. 
NOTE: advice here is generic golang advice for dealing with the time.Time objects and pointers.
Based on threads in the following PRs:
https://github.com/mongodb/mongodb-atlas-cli/pull/2096
https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1324

CLOUDP-191409: date field best practices

---

tools/releaser/README.md

Update releaser README to omit redundant step

---

.github/workflows/autorelease.yaml
.github/workflows/autoupdate-prod.yaml

fix: minor improvements to pipeline

---

.github/workflows/issues.yml

This PR adds jira automation to automatically create jira for every GitHub issue we have.
EDIT:
Need to figure out secret values.

fix: add jira integration to the SDK

---

.github/workflows/issues.yml

Adding required payload for CLOUDP jira to automation job

CLOUDP-192315: missing team assignment

---

.github/workflows/autoupdate-preview.yaml

Renaming dev to preview for more clarity for maintenance plan

CLOUDP-186948: change job from dev to preview

---

tools/transformer/README.md

Covering 2 transformations that were not documented

fix: add missing transformation docs

---

.github/dependabot.yml

chore(deps): enable dependabot for npm

---

auth/doc.go

Tried using this code example and several immediate Go issues, fixed.

Correct code example in auth/doc.go

---

docs/doc_1_concepts.md

Applies a copy review for https://github.com/mongodb/atlas-sdk-go/pull/160.

(DOCSP-32233) Applies copy review for PR 160

---

tools/package-lock.json
tools/package.json

Reverts mongodb/atlas-sdk-go#157

Revert "chore(deps): bump @nestjs/core and @openapitools/openapi-generator-cli in /tools"

---

.github/workflows/autoupdate-preview.yaml

Fix Preview code example to make it copy/pastable 
If I try to use the copy/paste feature the pasted result include invalid characters

fix: update preview code example

---

.github/workflows/autoupdate-preview.yaml
.github/workflows/autoupdate-prod.yaml
.github/workflows/pr.yml

Make sure the GH actions use the same go version

task (build): use go mod go version for all github actions

---

go.mod

task: update go version to 1.20

---

.github/workflows/autoupdate-preview.yaml

Reference for the secret contains extra space.
CC @gssbzn

fix: invalid reference in the dev job

---

.github/workflows/breaking-changes.yaml
.github/workflows/pr.yml

fix: fix PR checks

---

tools/releaser/scripts/setghenv.sh

Improve the release notes generation by adding a line break on the breaking chnages

task: improve release notes

---

tools/scripts/fetch.sh

Improve how the preview does its thing to get some more details on a current failure

task: improve the order and logs for preview job

---

MAINTENANCE.md

doc: reference generation workflow under releases to provide additional information

---

tools/releaser/scripts/new-version.sh

We should use the local variable `NEW_MAJOR_VERSION` instead.

CLOUDP-203325: update version variable for breaking changes

---

.github/workflows/autoupdate-prod.yaml

Add note about the need to reopen PR to trigger builds.

Improve PR description of the automatic PR

---

.github/workflows/autoupdate-prod.yaml

Allow empty commits for openapi.

fix: check for modifications after openapi fetch

---

.github/workflows/autoupdate-prod.yaml

The previous step started to remove previously installed node_modules.
We need to ensure that npm packages are installed properly by issuing extra npm install

task: make sure that pipeline installs node packages before formatting

---

.github/dependabot.yml

fix: ignore tj-actions from frequent updates

---

docs/doc_5_best_practices.md
examples/download/downloadLogs.go

Atlas Go SDK docs changes for binary responses
Link to any related issue(s): https://jira.mongodb.org/browse/CLOUDP-213199

CLOUDP-213199 Atlas Go SDK docs changes for binary responses

---

docs/doc_5_best_practices.md

Documentation for pointers covering recent introduction of arrays and optionals

CLOUDP-196988: pointer handling

---

admin/utils.go
admin/utils_test.go
internal/core/version.go
test/utils_test.go
tools/config/go-templates/utils.mustache

Including changes from: https://github.com/mongodb/atlas-sdk-go/pull/268

admin/utils.go: add helper methods for parsing and pointer handling

---

docs/doc_5_best_practices.md

Please include a summary of the fix/feature/change, including any relevant motivation and context.

(DOCSP-35705) Fixes broken link, updates numbering to bullets

---

docs/doc_2_error_handling.md

Update docs with example of handling HTTP response status codes

Update docs with example of handling HTTP response status codes

---

tools/scripts/generate_mocks.sh

Fixes permissions in Mockery generated files so it uses current user instead of root.

chore: Fixes permissions in Mockery generated files

---

internal/core/version.go

task: release version

---

admin/atlas_client.go
tools/config/go-templates/atlas_client.mustache

Minor tweak to extend docs for user facing helper methods with more details.
Fixes #303

CLOUDP-240738: use digest documentation

---

README.md

Badge will show golang version that sdk uses

task: add golang badge

---

admin/client.go
tools/config/go-templates/client.mustache

Remove unneeded if check flagged by linting.

chore: remove unneeded if check flagged by linting

---

tools/releaser/scripts/update-version.sh

Adjusting script so we can go higher than 10 breaking releases :) 
[CLOUDP-245134](https://jira.mongodb.org/browse/CLOUDP-245134)

CLOUDP-245134: minor tweak in release script for version bumps

---

Makefile

Add goimports install to openapi-pipeline
Link to any related issue(s):  CLOUDP-252328

CLOUDP-252328 Add goimports install to openapi-pipeline

---

examples/go.mod
tools/releaser/scripts/version-paths.sh

Include examples go.mod update in the SDK release update paths.
Otherwise examples rely on the released version of the SDKs.

task: update examples go mod file

---

docs/doc_1_concepts.md
docs/doc_2_error_handling.md
docs/doc_3_migration.md
docs/doc_4_authentication.md
docs/doc_5_best_practices.md

CLOUDP-251055: Code example for authentication via Go SDK doesn't work (sdk/go/authentication)

---

docs/doc_2_error_handling.md
examples/mock/cluster_test.go

Added mocking tests + documentation changes covering mocking
Link to any related issue(s):  CLOUDP-242668

CLOUDP-242668: mocking tests + documentation changes

---

docs/doc_5_best_practices.md

Applies a copy review to new section in the docs
Note: I removed the line about referring to documentation. Unless we can link to the documentation we mean, we should omit this (please provide a link if possible). Thanks!

(DOCSP-41487) Applies copy review to new section in Best Practices

---

.github/workflows/autoupdate-prod.yaml

Adds verify changed files before commit operation preventing job failures

task: verify changed files before commit

---

tools/releaser/scripts/breaking-changes.sh

Minor improvements in the breaking changes script in order to gain more information about breaking changes detection
1. Added bunch of new methods
> Breaking changes finished with 0 return code
> Non-breaking changes detected
2. Added breaking change
> Breaking changes finished with 0 return code
Detected major breaking changes in the release
Breaking changes for the major release
> go.mongodb.org/atlas-sdk/v20240805003/admin
Incompatible changes:
>  - (*SearchSynonymMappingDefinition).GetName: removed
>  - (*SearchSynonymMappingDefinition).SetAnalyzer: removed
> - NewSearchSynonymMappingDefinition: removed

CLOUDP-261727: improved script for breaking changes detection

---

tools/releaser/scripts/breaking-changes.sh

Breaking changes file variable was set to empty.

fix: prevent unbound variable

---

internal/core/version.go

Manual release bump

---

.tool-versions
go.mod

task: update min go version

---

.github/CODEOWNERS

Updates codeowners removing unneeded rules.

chore Updates codeowners

---

.github/workflows/autoupdate-preview.yaml
.github/workflows/autoupdate-prod.yaml

Uses APIx integration bot account
Link to any related issue(s):  CLOUDP-271186

chore: Uses APIx integration bot account

---

examples/go.mod

Update the example, Go keeps trying to also update this file so I want to commit the change t avoid doing it by accident

task: update example go

---

.github/workflows/autoupdate-preview.yaml
.github/workflows/autoupdate-prod.yaml

Removes token when creating PR

task: Removes token when creating PR

---

.github/workflows/autoupdate-preview.yaml
.github/workflows/autoupdate-prod.yaml

task: Uses token when creating PR

---

.github/CODEOWNERS

Adds doc exemption code owners

task: Adds doc exemption code owners

---

.github/workflows/autoupdate-preview.yaml

Updates link in Preview GHA to the latest version, so it will be automatically updated when new versions are created.
Link to any related issue(s):  CLOUDP-276361

task: Updates link in Preview GHA

---

.github/workflows/autoupdate-prod.yaml

Adjust Autoupdate PR doc as reopen PR is not needed any more to trigger PR checks

task: Adjust Autoupdate PR doc

---

.github/workflows/pr.yml
Makefile
examples/aws_cluster/aws.go
examples/mock/cluster_test.go

CLOUDP-272624: fixed example

---

.github/workflows/issues.yml

Adapts Issues GitHub action. Folows TF repo, and changes assignee team.
Link to any related issue(s): CLOUDP-278645

chore: Adapts Issues GitHub action

---

MAINTENANCE.md

Small note update from apix1 team

task: update note in maintenance

---

auth/credentials/api.go
auth/credentials/transport.go

We need to have logic to trim not relevant `/` from base urls.

CLOUDP-279932: trim suffix when provided base url contains /

---

admin/client.go
tools/config/go-templates/client.mustache
tools/config/go-templates/configuration.mustache

CLOUDP-280943: remove not used template references to OAuth

---

examples/auth/basic_client.go
examples/auth_advanced/advanced_client.go
examples/service_account/sa_management.go

Adding example for Service Account Management API covering creating new client and performing requests. 
Example also adds secret management and rotation which is useful to clarify. 
1.  go run ./examples/service_account/sa_management.go
2. Checked UI for creation and experimented with updating SA state in UI and Programmatically

CLOUDP-180059: Service Accounts Example

---

docs/doc_4_authentication.md

Service Account OAuth package documentation.

CLOUDP-279933: documentation

---

docs/doc_4_authentication.md
examples/oauthcache/cached_token.go
examples/service_account_token_store/cached_token.go

Adding cache example source code + documentation
Original change developed by @gssbzn.
I have extended it by extra comments and added documentation.

CLOUDP-282641: Addding example for saving OAuth token

---

internal/core/version.go

Bumps version for minor release to v20241113004.1.0
Link to any related issue(s): [CLOUDP-279222](https://jira.mongodb.org/browse/CLOUDP-279222)

chore: Bumps version for minor release to v20241113004.1.0

---

examples/service_account_management/sa_management.go

Small improvement to the example

task: improve sa management example

---

.github/dependabot.yml

dependabot seems to be not working for NPM trying to pint it to the folder, also updating the reviewer to integrations

task: update dependabot for npm

---

tools/transformer/src/atlasTransformations.js
tools/transformer/src/engine/readers.js
tools/transformer/src/engine/transformers.js
tools/transformer/src/transformations/additionalPropertiesObject.js
tools/transformer/src/transformations/anyOf.js
tools/transformer/src/transformations/discriminator.js
tools/transformer/src/transformations/index.js
tools/transformer/src/transformations/oneOf.js

Fix multiple typos in the code base

task: fix typos

---

auth/code/oauth.go

Related GH issue https://github.com/mongodb/atlas-sdk-go/issues/528

chore: Remove redundant conditional

---

.github/workflows/autoupdate-preview.yaml
.github/workflows/autoupdate-prod.yaml

Change verify-changed-files Github action. Follows same approach as in: https://github.com/mongodb/mongodb-atlas-local/pull/343
Link to any related issue(s): CLOUDP-306816
- Example of SDK Preview GHA execution [here](https://github.com/mongodb/atlas-sdk-go/actions/runs/14215578647/job/39831433680) 
- Example of Generate SDK execution [here](https://github.com/mongodb/atlas-sdk-go/actions/runs/14215586686/job/39831457684)

chore: Change verify-changed-files Github action

---

.github/workflows/autoupdate-preview.yaml

Update GH Action to create SDK Preview PR in non-draft mode

chore: Update GH Action to create SDK Preview PR in non-draft mode
